// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPL9iZ9l3E36mXqRbCLHSI1nrrNRi8rbY',
    appId: '1:957283610837:web:72fb42f5851a747fe0f25c',
    messagingSenderId: '957283610837',
    projectId: 'serveeasy-project',
    authDomain: 'serveeasy-project.firebaseapp.com',
    storageBucket: 'serveeasy-project.appspot.com',
    measurementId: 'G-7LGNEMZS4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPIrfqSznmylUEi0eb3gmWdGY3oHoTNE',
    appId: '1:957283610837:android:c985d62e1bd46f0ae0f25c',
    messagingSenderId: '957283610837',
    projectId: 'serveeasy-project',
    storageBucket: 'serveeasy-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yia8YGl-hwLv8j4flRoP40MXfrFNn00',
    appId: '1:957283610837:ios:ad66d48e1c7a083be0f25c',
    messagingSenderId: '957283610837',
    projectId: 'serveeasy-project',
    storageBucket: 'serveeasy-project.appspot.com',
    iosClientId: '957283610837-skbi11u6i0924es5hhvlf55pk90ps3h2.apps.googleusercontent.com',
    iosBundleId: 'com.app.serveeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-yia8YGl-hwLv8j4flRoP40MXfrFNn00',
    appId: '1:957283610837:ios:db09d73bc8693c4ae0f25c',
    messagingSenderId: '957283610837',
    projectId: 'serveeasy-project',
    storageBucket: 'serveeasy-project.appspot.com',
    iosClientId: '957283610837-ne79ob5nn6dflvd43mmu245k81oap9sa.apps.googleusercontent.com',
    iosBundleId: 'com.app.serveeasy.serveeasyApp',
  );
}
